name: 🍏 iOS Simulator Template Export
on:
  workflow_call:
  workflow_dispatch:

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: 3.6
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios-simulator
  cancel-in-progress: true

jobs:
  ios-simulator-template:
    runs-on: "macos-latest"
    name: iOS Simulator Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v4

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ios-simulator-template
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation (x86_64 simulator)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=x86_64 ios_simulator=yes
          platform: iphone
          target: release
          tools: false

      - name: Compilation (arm64 simulator)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=arm64 ios_simulator=yes
          platform: iphone
          target: release
          tools: false

      - name: Create universal binary
        run: |
          lipo -create ./bin/libgodot.iphone.opt.x86_64.simulator.a ./bin/libgodot.iphone.opt.arm64.simulator.a -output ./bin/libgodot.iphone.opt.simulator.a

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ios-simulator-template
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ios-simulator-template
